const Constants = {
  USER_LOGGEDIN: "USER_LOGGEDIN",
  USER_LOGOUT: "USER_LOGOUT",
  FETCH_CUSTOMERS: "FETCH_CUSTOMERS",
  FETCH_CUSTOMER: "FETCH_CUSTOMER",
  SET_CUSTOMER: "SET_CUSTOMER",
  NEW_POST: "NEW_POST"
};

export default Constants;